"""added age

Revision ID: 657b9d5d2f9e
Revises: 3c499830c805
Create Date: 2024-10-01 10:04:07.826113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657b9d5d2f9e'
down_revision = '3c499830c805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['age'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
